name: llm_wrapper_jb
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - numpy==2.3.5
      - pandas==2.2.3
      - scipy==1.17.0
      - numba==0.63.1
      - statsmodels==0.14.6
      - scikit-learn==1.8.0
      - loguru==0.7.2
      - openpyxl==3.1.5
      - xlrd >= 2.0.1
      - xlsxwriter==3.2.9
      - pyarrow==23.0.0
      - boto3==1.42.30
      - plotly==6.5.2
      - matplotlib==3.10.8
      - tornado==6.5.4
      - fastparquet==2025.12.0
      - botocore==1.42.30
      - yfinance==1.1.0
      - pytest==9.0.2
      - pandas-stubs==2.2.3.250308
      - scipy-stubs==1.17.0.1
      - pandas_datareader==0.10.0
      - psutil==7.2.1
      - pywin32
      - jinja2==3.1.6
      - paramiko==4.0.0
      - extract-msg==0.55.0
      - openai==2.16.0
      - playwright==1.58.0
      - slack_sdk==3.39.0
      - reportlab==4.4.9
      - pypdf==6.6.2
      - joblib==1.5.3
      - html5lib==1.1